"""Add isActive column to User

Revision ID: c2b12e2d60d3
Revises: 
Create Date: 2025-12-14 19:36:58.584310+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c2b12e2d60d3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'createdAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('book', 'updatedAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.drop_index(op.f('ix_book_id'), table_name='book')
    op.alter_column('cart', 'createdAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('cart', 'updatedAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('favorite', 'createdAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('favorite', 'updatedAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('order', 'orderDate',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('order', 'createdAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('order', 'updatedAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.add_column('orderItem', sa.Column('is_settled', sa.Boolean(), nullable=False))
    op.alter_column('orderItem', 'createdAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('orderItem', 'updatedAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('ranking', 'createdAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('ranking', 'updatedAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('review', 'createdAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('review', 'updatedAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('saleBookList', 'createdAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('saleBookList', 'updatedAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.add_column('saleInform', sa.Column('discountRate', sa.DECIMAL(precision=5, scale=2), nullable=False))
    op.alter_column('saleInform', 'createdAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('saleInform', 'updatedAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.drop_column('saleInform', 'discoutRate')
    op.alter_column('sellerProfiles', 'createdAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('sellerProfiles', 'updatedAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('settlement', 'createdAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('settlement', 'updatedAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('settlementOrder', 'createdAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('settlementOrder', 'updatedAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.add_column('user', sa.Column('isActive', sa.Boolean(), nullable=False))
    op.alter_column('user', 'createdAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('user', 'updatedAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.drop_index(op.f('ix_user_id'), table_name='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.alter_column('user', 'updatedAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.alter_column('user', 'createdAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.drop_column('user', 'isActive')
    op.alter_column('settlementOrder', 'updatedAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.alter_column('settlementOrder', 'createdAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.alter_column('settlement', 'updatedAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.alter_column('settlement', 'createdAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.alter_column('sellerProfiles', 'updatedAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.alter_column('sellerProfiles', 'createdAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.add_column('saleInform', sa.Column('discoutRate', mysql.DECIMAL(precision=5, scale=2), nullable=False))
    op.alter_column('saleInform', 'updatedAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.alter_column('saleInform', 'createdAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.drop_column('saleInform', 'discountRate')
    op.alter_column('saleBookList', 'updatedAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.alter_column('saleBookList', 'createdAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.alter_column('review', 'updatedAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.alter_column('review', 'createdAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.alter_column('ranking', 'updatedAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.alter_column('ranking', 'createdAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.alter_column('orderItem', 'updatedAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.alter_column('orderItem', 'createdAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.drop_column('orderItem', 'is_settled')
    op.alter_column('order', 'updatedAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.alter_column('order', 'createdAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.alter_column('order', 'orderDate',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('favorite', 'updatedAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.alter_column('favorite', 'createdAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.alter_column('cart', 'updatedAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.alter_column('cart', 'createdAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.create_index(op.f('ix_book_id'), 'book', ['id'], unique=False)
    op.alter_column('book', 'updatedAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.alter_column('book', 'createdAt',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('(now())'),
               nullable=True)
    # ### end Alembic commands ###
